# Enable AndroidX
android.useAndroidX=true

# Kotlin Code Style
kotlin.code.style=official

# JVM Heap Size
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Parallel builds
org.gradle.parallel=true
# Caching
org.gradle.caching=true

# Fix build: TODO review why neeeded
android.disallowKotlinSourceSets=false

org.gradle.configuration-cache=true
